syntax = "proto3";

package payment;

service PaymentService {
  rpc CreateCheckout (CreateCheckoutRequest) returns (CreateCheckoutResponse);
}

message CreateCheckoutRequest {
  string booking_id = 1;
  int32 amount = 2;
  string currency = 3;
  string organizer_account_id = 4;
  int32 quantity = 5;
  string ticket_type_name = 6;
  string success_url = 7;
}

message CreateCheckoutResponse {
  bool success = 1;
  string checkout_session_id = 2;
  string client_secret = 3;
  string message = 4;
}
