ALTER TABLE "tickets"
  ADD COLUMN IF NOT EXISTS "eventTitle" TEXT,
  ADD COLUMN IF NOT EXISTS "coverImageUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "venueName" TEXT,
  ADD COLUMN IF NOT EXISTS "venueAddress" TEXT,
  ADD COLUMN IF NOT EXISTS "startsAt" TIMESTAMPTZ(3),
  ADD COLUMN IF NOT EXISTS "endsAt" TIMESTAMPTZ(3),
  ADD COLUMN IF NOT EXISTS "timezone" TEXT,
  ADD COLUMN IF NOT EXISTS "unitPrice" DECIMAL(12,3),
  ADD COLUMN IF NOT EXISTS "currency" VARCHAR(3),
  ADD COLUMN IF NOT EXISTS "sessionVersion" INTEGER,
  ADD COLUMN IF NOT EXISTS "templateVersion" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "renderRevision" INTEGER NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS "tickets_ownerId_issuedAt_id_idx"
  ON "tickets" ("ownerId", "issuedAt" DESC, "id" DESC);
